In [1]:
# tensorflow version should be - 2.4 stable one and keras API
import numpy as np
import tensorflow as tf

In [2]:
with open('reviews.txt','r') as f:
    reviews = f.read()
with open('labels.txt','r') as f:
    labels = f.read()

In [3]:
# reviews
reviews[:300]

'Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life, such as "Teachers". My 35 years in the teaching profession lead me to believe that Bromwell High\'s satire is much closer to reality than is "Teachers". The scramble to survive financially, the insigh'

In [4]:
labels

'positive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative'

# Data Preprocessing

In [5]:
type(reviews)

str

In [6]:
[c for c in reviews]

['B',
 'r',
 'o',
 'm',
 'w',
 'e',
 'l',
 'l',
 ' ',
 'H',
 'i',
 'g',
 'h',
 ' ',
 'i',
 's',
 ' ',
 'a',
 ' ',
 'c',
 'a',
 'r',
 't',
 'o',
 'o',
 'n',
 ' ',
 'c',
 'o',
 'm',
 'e',
 'd',
 'y',
 '.',
 ' ',
 'I',
 't',
 ' ',
 'r',
 'a',
 'n',
 ' ',
 'a',
 't',
 ' ',
 't',
 'h',
 'e',
 ' ',
 's',
 'a',
 'm',
 'e',
 ' ',
 't',
 'i',
 'm',
 'e',
 ' ',
 'a',
 's',
 ' ',
 's',
 'o',
 'm',
 'e',
 ' ',
 'o',
 't',
 'h',
 'e',
 'r',
 ' ',
 'p',
 'r',
 'o',
 'g',
 'r',
 'a',
 'm',
 's',
 ' ',
 'a',
 'b',
 'o',
 'u',
 't',
 ' ',
 's',
 'c',
 'h',
 'o',
 'o',
 'l',
 ' ',
 'l',
 'i',
 'f',
 'e',
 ',',
 ' ',
 's',
 'u',
 'c',
 'h',
 ' ',
 'a',
 's',
 ' ',
 '"',
 'T',
 'e',
 'a',
 'c',
 'h',
 'e',
 'r',
 's',
 '"',
 '.',
 ' ',
 'M',
 'y',
 ' ',
 '3',
 '5',
 ' ',
 'y',
 'e',
 'a',
 'r',
 's',
 ' ',
 'i',
 'n',
 ' ',
 't',
 'h',
 'e',
 ' ',
 't',
 'e',
 'a',
 'c',
 'h',
 'i',
 'n',
 'g',
 ' ',
 'p',
 'r',
 'o',
 'f',
 'e',
 's',
 's',
 'i',
 'o',
 'n',
 ' ',
 'l',
 'e',
 'a',
 'd',
 ' ',
 'm',
 'e'

In [7]:
import string
punctuation

NameError: name 'punctuation' is not defined

In [8]:
from string import punctuation
all_text = ''.join([c for c in reviews if c not in punctuation])
reviews = all_text.split('\n')
# print(reviews[2:3])
print(reviews[4:5])
all_text = ' '.join(reviews)
words = all_text.split()

['Wheres the wit Wheres the cleverness Where are some friggin DECENT JOKES Not in this piece of trash thats for sure']


In [9]:
words

['Bromwell',
 'High',
 'is',
 'a',
 'cartoon',
 'comedy',
 'It',
 'ran',
 'at',
 'the',
 'same',
 'time',
 'as',
 'some',
 'other',
 'programs',
 'about',
 'school',
 'life',
 'such',
 'as',
 'Teachers',
 'My',
 '35',
 'years',
 'in',
 'the',
 'teaching',
 'profession',
 'lead',
 'me',
 'to',
 'believe',
 'that',
 'Bromwell',
 'Highs',
 'satire',
 'is',
 'much',
 'closer',
 'to',
 'reality',
 'than',
 'is',
 'Teachers',
 'The',
 'scramble',
 'to',
 'survive',
 'financially',
 'the',
 'insightful',
 'students',
 'who',
 'can',
 'see',
 'right',
 'through',
 'their',
 'pathetic',
 'teachers',
 'pomp',
 'the',
 'pettiness',
 'of',
 'the',
 'whole',
 'situation',
 'all',
 'remind',
 'me',
 'of',
 'the',
 'schools',
 'I',
 'knew',
 'and',
 'their',
 'students',
 'When',
 'I',
 'saw',
 'the',
 'episode',
 'in',
 'which',
 'a',
 'student',
 'repeatedly',
 'tried',
 'to',
 'burn',
 'down',
 'the',
 'school',
 'I',
 'immediately',
 'recalled',
 'at',
 'High',
 'A',
 'classic',
 'line',
 'INSPEC

In [10]:
len(words)

1161

In [11]:
words[1:3]

['High', 'is']

In [12]:
all_text[9]

'H'

# Econding the words

In [13]:
sample = " Jateendra Kumar Pradhan how are you how do you do What up and how are you taking"
sample.split()

['Jateendra',
 'Kumar',
 'Pradhan',
 'how',
 'are',
 'you',
 'how',
 'do',
 'you',
 'do',
 'What',
 'up',
 'and',
 'how',
 'are',
 'you',
 'taking']

In [14]:
from collections import Counter
counts1 = Counter(sample)
vocab1 = sorted(counts1, key=counts1.get, reverse=True)
vocab1

[' ',
 'a',
 'o',
 'd',
 'r',
 'u',
 'h',
 'e',
 'n',
 't',
 'w',
 'y',
 'J',
 'K',
 'm',
 'P',
 'W',
 'p',
 'k',
 'i',
 'g']

In [15]:
# Hash our data - means indexing , so searching will be easier . So for every word it will generate numerical value .

In [16]:
from collections import Counter
counts = Counter(words)
counts

Counter({'Bromwell': 8,
         'High': 6,
         'is': 35,
         'a': 24,
         'cartoon': 3,
         'comedy': 1,
         'It': 2,
         'ran': 1,
         'at': 5,
         'the': 34,
         'same': 1,
         'time': 3,
         'as': 3,
         'some': 6,
         'other': 2,
         'programs': 1,
         'about': 6,
         'school': 5,
         'life': 4,
         'such': 2,
         'Teachers': 2,
         'My': 1,
         '35': 1,
         'years': 2,
         'in': 9,
         'teaching': 1,
         'profession': 1,
         'lead': 1,
         'me': 3,
         'to': 19,
         'believe': 1,
         'that': 13,
         'Highs': 1,
         'satire': 1,
         'much': 4,
         'closer': 1,
         'reality': 1,
         'than': 2,
         'The': 9,
         'scramble': 1,
         'survive': 1,
         'financially': 1,
         'insightful': 1,
         'students': 7,
         'who': 5,
         'can': 1,
         'see': 2,
         'right

In [17]:
sorted(counts)

['1015',
 '35',
 '7510',
 '930',
 'A',
 'Afghani',
 'Am',
 'As',
 'Basically',
 'Because',
 'Bell',
 'British',
 'Bromwell',
 'By',
 'Canadian',
 'Cartoon',
 'Combination',
 'Comes',
 'Cussing',
 'DECENT',
 'Ditch',
 'Even',
 'Ever',
 'Everything',
 'Expertly',
 'Family',
 'Following',
 'For',
 'Futurama',
 'Glorbacks',
 'Goddam',
 'Guy',
 'Hells',
 'High',
 'Highs',
 'Hilarity',
 'How',
 'However',
 'I',
 'INSPECTOR',
 'Id',
 'If',
 'Im',
 'In',
 'Indian',
 'Iqbals',
 'It',
 'Its',
 'JOKES',
 'Keisha',
 'LIFE',
 'Latrina',
 'Like',
 'London',
 'Mike',
 'My',
 'NOTHING',
 'Natella',
 'Nice',
 'No',
 'Not',
 'Nothing',
 'OK',
 'Or',
 'Overplaying',
 'Park',
 'Political',
 'Public',
 'REAL',
 'Really',
 'STUDENT',
 'Saved',
 'School',
 'South',
 'Swearing',
 'TBS',
 'TV',
 'Teachers',
 'Teletoon',
 'Thats',
 'The',
 'There',
 'This',
 'Try',
 'Tyson',
 'Unfunny',
 'Unoriginal',
 'Very',
 'WB',
 'Watch',
 'Welcome',
 'Western',
 'What',
 'When',
 'Where',
 'Wheres',
 'Which',
 'With',
 'Y

In [18]:
from collections import Counter
counts = Counter(words)
vocab = sorted(counts, key=counts.get, reverse=True)
vocab

['is',
 'the',
 'and',
 'of',
 'a',
 'it',
 'to',
 'you',
 'this',
 'I',
 'show',
 'that',
 'have',
 'be',
 'funny',
 'in',
 'The',
 'or',
 'Bromwell',
 'for',
 'not',
 'students',
 'your',
 'like',
 'but',
 'on',
 'an',
 'High',
 'some',
 'about',
 'nothing',
 'at',
 'school',
 'who',
 'are',
 'South',
 'with',
 'girl',
 'watch',
 'life',
 'much',
 'teachers',
 'think',
 'animated',
 'shows',
 'makes',
 'Family',
 'Guy',
 'Park',
 'them',
 'because',
 'white',
 'ultra',
 'too',
 'what',
 'dont',
 'every',
 'cartoon',
 'time',
 'as',
 'me',
 'right',
 'their',
 'all',
 'one',
 'my',
 'most',
 'This',
 'actually',
 'trash',
 'TV',
 'witty',
 'more',
 'Its',
 'characters',
 'violent',
 'stupid',
 'did',
 'something',
 'slutty',
 'his',
 'British',
 'Keisha',
 'Natella',
 'Latrina',
 'do',
 'fun',
 'sharp',
 'if',
 'watching',
 'though',
 'may',
 'very',
 'know',
 'out',
 'high',
 'subject',
 'just',
 'doesnt',
 'then',
 'It',
 'other',
 'such',
 'Teachers',
 'years',
 'than',
 'see',
 'e

In [19]:
# enumeration - generates sequential indexing . Counts generates numbers . 
for i,word in enumerate(vocab, 1):
    print(i , word)

1 is
2 the
3 and
4 of
5 a
6 it
7 to
8 you
9 this
10 I
11 show
12 that
13 have
14 be
15 funny
16 in
17 The
18 or
19 Bromwell
20 for
21 not
22 students
23 your
24 like
25 but
26 on
27 an
28 High
29 some
30 about
31 nothing
32 at
33 school
34 who
35 are
36 South
37 with
38 girl
39 watch
40 life
41 much
42 teachers
43 think
44 animated
45 shows
46 makes
47 Family
48 Guy
49 Park
50 them
51 because
52 white
53 ultra
54 too
55 what
56 dont
57 every
58 cartoon
59 time
60 as
61 me
62 right
63 their
64 all
65 one
66 my
67 most
68 This
69 actually
70 trash
71 TV
72 witty
73 more
74 Its
75 characters
76 violent
77 stupid
78 did
79 something
80 slutty
81 his
82 British
83 Keisha
84 Natella
85 Latrina
86 do
87 fun
88 sharp
89 if
90 watching
91 though
92 may
93 very
94 know
95 out
96 high
97 subject
98 just
99 doesnt
100 then
101 It
102 other
103 such
104 Teachers
105 years
106 than
107 see
108 episode
109 down
110 Im
111 expect
112 many
113 What
114 animation
115 writing
116 funnier
117 better
118 C

In [20]:
# We can use Hashing numbers here or enumeration . 
# Hashing can be used for sort , searching operation . May not use for Embedding purposes . But your choice .
# Drawback of Hashing is : It generates any kind of numbers . 1 , 100023 , etc . So data variations will be very high .
# So Normal distribution of the data is too scattered .

In [21]:
vocab_to_int = {word: i for i,word in enumerate(vocab, 1)} # start from 1

In [22]:
vocab_to_int

{'is': 1,
 'the': 2,
 'and': 3,
 'of': 4,
 'a': 5,
 'it': 6,
 'to': 7,
 'you': 8,
 'this': 9,
 'I': 10,
 'show': 11,
 'that': 12,
 'have': 13,
 'be': 14,
 'funny': 15,
 'in': 16,
 'The': 17,
 'or': 18,
 'Bromwell': 19,
 'for': 20,
 'not': 21,
 'students': 22,
 'your': 23,
 'like': 24,
 'but': 25,
 'on': 26,
 'an': 27,
 'High': 28,
 'some': 29,
 'about': 30,
 'nothing': 31,
 'at': 32,
 'school': 33,
 'who': 34,
 'are': 35,
 'South': 36,
 'with': 37,
 'girl': 38,
 'watch': 39,
 'life': 40,
 'much': 41,
 'teachers': 42,
 'think': 43,
 'animated': 44,
 'shows': 45,
 'makes': 46,
 'Family': 47,
 'Guy': 48,
 'Park': 49,
 'them': 50,
 'because': 51,
 'white': 52,
 'ultra': 53,
 'too': 54,
 'what': 55,
 'dont': 56,
 'every': 57,
 'cartoon': 58,
 'time': 59,
 'as': 60,
 'me': 61,
 'right': 62,
 'their': 63,
 'all': 64,
 'one': 65,
 'my': 66,
 'most': 67,
 'This': 68,
 'actually': 69,
 'trash': 70,
 'TV': 71,
 'witty': 72,
 'more': 73,
 'Its': 74,
 'characters': 75,
 'violent': 76,
 'stupid': 77

In [23]:
# from collections import Counter
# counts = Counter(words)
# vocab = sorted(counts, key=counts.get, reverse=True)

# # Create your dictionary that maps vocab words to integers here
# vocab_to_int = {word: i for i, word in enumerate(vocab, 1)} # starts from 1

# # Convert the reviews to integers, same shape as reviews list, but with integers
# review_ints = []
# for each in reviews:
#     review_ints.append([vocab_to_int[word] for word in each.split()])

In [24]:
review_ints = []
for each in reviews:
    review_ints.append([vocab_to_int[word] for word in each.split()])

In [25]:
review_ints

[[19,
  28,
  1,
  5,
  58,
  168,
  101,
  169,
  32,
  2,
  170,
  59,
  60,
  29,
  102,
  171,
  30,
  33,
  40,
  103,
  60,
  104,
  172,
  173,
  105,
  16,
  2,
  174,
  175,
  176,
  61,
  7,
  177,
  12,
  19,
  178,
  179,
  1,
  41,
  180,
  7,
  181,
  106,
  1,
  104,
  17,
  182,
  7,
  183,
  184,
  2,
  185,
  22,
  34,
  186,
  107,
  62,
  187,
  63,
  188,
  42,
  189,
  2,
  190,
  4,
  2,
  191,
  192,
  64,
  193,
  61,
  4,
  2,
  194,
  10,
  195,
  3,
  63,
  22,
  196,
  10,
  197,
  2,
  108,
  16,
  198,
  5,
  199,
  200,
  201,
  7,
  202,
  109,
  2,
  33,
  10,
  203,
  204,
  32,
  28,
  205,
  206,
  207,
  208,
  110,
  209,
  7,
  210,
  65,
  4,
  23,
  42,
  211,
  212,
  7,
  19,
  28,
  10,
  111,
  12,
  112,
  213,
  4,
  66,
  214,
  43,
  12,
  19,
  28,
  1,
  215,
  216,
  113,
  5,
  217,
  12,
  6,
  218],
 [219,
  24,
  2,
  114,
  220,
  221,
  4,
  222,
  223,
  3,
  115,
  224,
  14,
  5,
  225,
  116,
  25,
  9,
  1,
  117,
  106,
 

In [26]:
review_ints[1]

[219,
 24,
 2,
 114,
 220,
 221,
 4,
 222,
 223,
 3,
 115,
 224,
 14,
 5,
 225,
 116,
 25,
 9,
 1,
 117,
 106,
 67,
 118,
 44,
 45,
 226,
 24,
 10,
 227,
 228,
 29,
 229,
 119,
 114]

In [27]:
len(review_ints[15])

4

# Encoding the labels

In [28]:
labels

'positive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative\npositive\nnegative'

In [29]:
labels = labels.split('\n')
labels

['positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative']

In [30]:
[1 if label == 'positive' else 0 for label in labels]

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

In [31]:
labels = [1 if label == 'positive' else 0 for label in labels]

In [32]:
len(labels)

20

In [33]:
labels = np.array(labels)
labels

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [34]:
#labels = np.array([1 if label == 'positive' else 0 for label in labels])

In [35]:
labels

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [36]:
labels[1:10]

array([0, 1, 0, 1, 0, 1, 0, 1, 0])

In [37]:
reviews[1:2]

['Really like the animation style Combination of voice work and writing could be a lot funnier but this is better than most Canadian animated shows elevated like I said by some really good animation']

In [38]:
review_lens = Counter([len(x) for x in review_ints])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))

Zero-length reviews: 13
Maximum review length: 200


In [39]:
review_lens

Counter({138: 1,
         34: 1,
         20: 1,
         0: 13,
         21: 1,
         63: 1,
         45: 1,
         6: 2,
         76: 1,
         35: 1,
         4: 1,
         30: 1,
         52: 1,
         13: 1,
         32: 1,
         200: 1,
         16: 1,
         112: 1,
         144: 1,
         114: 1})

In [40]:
# Filter out that review with 0 Length
review_ints = [review for review in review_ints if (len(review) > 0)]

In [41]:
review_ints

[[19,
  28,
  1,
  5,
  58,
  168,
  101,
  169,
  32,
  2,
  170,
  59,
  60,
  29,
  102,
  171,
  30,
  33,
  40,
  103,
  60,
  104,
  172,
  173,
  105,
  16,
  2,
  174,
  175,
  176,
  61,
  7,
  177,
  12,
  19,
  178,
  179,
  1,
  41,
  180,
  7,
  181,
  106,
  1,
  104,
  17,
  182,
  7,
  183,
  184,
  2,
  185,
  22,
  34,
  186,
  107,
  62,
  187,
  63,
  188,
  42,
  189,
  2,
  190,
  4,
  2,
  191,
  192,
  64,
  193,
  61,
  4,
  2,
  194,
  10,
  195,
  3,
  63,
  22,
  196,
  10,
  197,
  2,
  108,
  16,
  198,
  5,
  199,
  200,
  201,
  7,
  202,
  109,
  2,
  33,
  10,
  203,
  204,
  32,
  28,
  205,
  206,
  207,
  208,
  110,
  209,
  7,
  210,
  65,
  4,
  23,
  42,
  211,
  212,
  7,
  19,
  28,
  10,
  111,
  12,
  112,
  213,
  4,
  66,
  214,
  43,
  12,
  19,
  28,
  1,
  215,
  216,
  113,
  5,
  217,
  12,
  6,
  218],
 [219,
  24,
  2,
  114,
  220,
  221,
  4,
  222,
  223,
  3,
  115,
  224,
  14,
  5,
  225,
  116,
  25,
  9,
  1,
  117,
  106,
 

In [42]:
review_ints[4]

[242,
 243,
 36,
 49,
 244,
 245,
 246,
 13,
 247,
 248,
 63,
 249,
 250,
 26,
 2,
 71,
 3,
 251,
 50,
 37,
 252,
 51,
 12,
 46,
 50,
 253,
 254,
 125,
 1,
 255,
 256,
 72,
 18,
 126,
 30,
 9,
 11,
 18,
 32,
 257,
 31,
 72,
 18,
 126,
 12,
 258,
 259,
 127,
 27,
 260,
 11,
 3,
 261,
 5,
 73,
 262,
 263,
 7,
 264,
 265,
 4,
 266,
 267]

In [43]:
type(review_ints)

list

In [44]:
# Now create an array features that contains the data we will pass to the network . The data should come from review_ints,
# since we want to feed integers to the network . Each row should be 200 elements long . For reviews shorter than 200
# words, left pad with 0s . That is  , if the review is ['best','movie','ever'],[117,18,128] as intergers , the row will
# look like [0,0,0,....,0,117,18,128]. For reviews longer than 200 , use on the first 200 words as the feature vector.

# This isn't trivial and there are a bunch of ways to do this. But , if you are going to be building your own deep
# learning networks, you're going to have to get used to preparing your data.

In [45]:
pad = [0] * 6
pad

[0, 0, 0, 0, 0, 0]

In [46]:
padded_feature = pad + [1,23,345]
padded_feature

[0, 0, 0, 0, 0, 0, 1, 23, 345]

In [47]:
# seq_len = 200
seq_len = 40
features = []
for review in review_ints:
    review_len = len(review)
    len_diff = seq_len - review_len
    if len_diff <= 0:
        features.append(review[:seq_len])
        print(review[:seq_len])
    else:
        padding = [0] * len_diff
        padded_feature = padding + review
        features.append(padded_feature)
print()
features = np.asarray(features)

[19, 28, 1, 5, 58, 168, 101, 169, 32, 2, 170, 59, 60, 29, 102, 171, 30, 33, 40, 103, 60, 104, 172, 173, 105, 16, 2, 174, 175, 176, 61, 7, 177, 12, 19, 178, 179, 1, 41, 180]
[242, 243, 36, 49, 244, 245, 246, 13, 247, 248, 63, 249, 250, 26, 2, 71, 3, 251, 50, 37, 252, 51, 12, 46, 50, 253, 254, 125, 1, 255, 256, 72, 18, 126, 30, 9, 11, 18, 32, 257]
[74, 268, 269, 270, 4, 65, 271, 272, 75, 128, 17, 76, 129, 3, 77, 38, 78, 79, 76, 129, 18, 77, 17, 52, 70, 130, 78, 79, 273, 274, 3, 80, 17, 275, 276, 277, 278, 279, 12, 280]
[131, 9, 1, 15, 289, 290, 2, 291, 4, 132, 82, 292, 293, 3, 27, 294, 4, 295, 42, 3, 22, 83, 1, 2, 296, 38, 34, 1, 53, 77, 3, 53, 76, 84, 1, 2, 53, 297, 53, 298]
[17, 11, 1, 338, 119, 5, 136, 11, 32, 339, 20, 29, 137, 340, 341, 3, 342, 343, 8, 90, 134, 91, 29, 138, 92, 14, 31, 139, 17, 11, 1, 15, 91, 344, 110, 124, 345, 346, 111, 6]
[370, 371, 21, 143, 2, 11, 372, 36, 49, 373, 374, 375, 144, 376, 377, 1, 15, 378, 145, 35, 96, 33, 22, 123, 2, 136, 379, 96, 33, 22, 26, 380, 18

In [48]:
features[0]

array([ 19,  28,   1,   5,  58, 168, 101, 169,  32,   2, 170,  59,  60,
        29, 102, 171,  30,  33,  40, 103,  60, 104, 172, 173, 105,  16,
         2, 174, 175, 176,  61,   7, 177,  12,  19, 178, 179,   1,  41,
       180])

In [49]:
features[1]

array([  0,   0,   0,   0,   0,   0, 219,  24,   2, 114, 220, 221,   4,
       222, 223,   3, 115, 224,  14,   5, 225, 116,  25,   9,   1, 117,
       106,  67, 118,  44,  45, 226,  24,  10, 227, 228,  29, 229, 119,
       114])

In [50]:
features[2]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  68, 120,   7,  14,   2, 121,
       230,  11,   4,   2, 231, 232, 105, 101,  69,  46,  47,  48, 233,
        15])

In [51]:
len(features[3])

40

In [52]:
# Here we do the padding to convert my data to structured format or tabular format .
# All the above data are enumerated number .

# Training , Validation , Test

In [53]:
features.shape

(20, 40)

In [54]:
labels.shape

(20,)

In [55]:
# Split the data - training , validation and test sets

In [56]:
split_frac = 0.8
split_idx = int(len(features) * split_frac)

train_x , val_x = features[:split_idx], features[split_idx:]
train_y , val_y = labels[:split_idx], labels[:split_idx]

test_idx = int(len(val_x) * 0.5)
val_x, test_x = val_x[:test_idx], val_x[test_idx:]
val_y, test_y = val_y[:test_idx], val_y[test_idx:]

print("\t\tFeature Shapes")
print("Train set: \t\t{}".format(train_x.shape),
     "\nValidation set: \t{}".format(val_x.shape),
     "\nTest set: \t\t{}".format(test_x.shape))

		Feature Shapes
Train set: 		(16, 40) 
Validation set: 	(2, 40) 
Test set: 		(2, 40)


In [57]:
val_x

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 434, 435,
         98,  39, 436, 437,  17, 438, 439, 146, 440,  96,  33, 144, 156,
         62],
       [441, 442,  54, 443, 444, 112, 138,   4,   9,  11,  78,   8,  69,
         39, 154,  23, 445, 157,   6, 446,  24,  30, 447,   4,  65, 448,
          6, 449,  54,  41,  20,   8,   7, 158,  19,   1,  31,  24,  36,
         49]])

In [58]:
test_x

array([[ 10,  13, 161, 474,  55,   8, 475,  35, 476,  30,  30,  68,  11,
         92,  21,  13,  93,  41,   4,   5, 477,  25,   6,   1,  93,  15,
         10,  39,   6, 478,  57, 479,   3, 160, 480, 137, 481,  59,  10,
         43],
       [ 19,  28,   1,  31, 495,   4, 496, 497, 498,   3, 499, 500,   9,
        501, 502,   4,   5,  22,   3,  42,  32,   5,  36, 503, 504, 505,
        506,   8, 507, 508,  37, 509,  74, 510, 511,  72,   3,  88,  17,
         75]])

In [59]:
split_idx = int(len(features) * split_frac)
split_idx

16

In [60]:
val_y

array([1, 0])

In [61]:
len(features)

20

# Simple RNN

In [63]:
import numpy as np

from sklearn.metrics import accuracy_score
from keras.datasets import reuters
# from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense,SimpleRNN,Activation
from keras import optimizers
from keras.wrappers.scikit_learn import KerasClassifier

# # Parameters for dataload
# num_words = 12
# maxlen = 50
# test_split = 0.3

# (X_train,y_train),(X_test,y_test) = reuters.load_data(num_words = num_words,max_len = maxlen , test_split = test_split)

# # pad the sequences with zeros
# # padding parameter is set to 'post' => 0's are appended to end of sequences
# X_train = pad_sequences(X_train, padding = 'post')
# X_test = pad_sequences(X_test,padding = 'post')

# X_train = np.array(X_train).reshape((X_train.shape[0],X_train.shape[1],1))
# X_test = np.array(X_test).reshape((X_test.shape[0],X_test.shape[1],1))

# y_data = np.concatenate((y_train,y_test))
# y_data = to_categorical(y_data)
# y_train = y_data[:1395]
# y_test = y_data[1395:]

def vanilla_rnn():
    model = Sequential()
    model.add(SimpleRNN(2, input_shape = (40,1) , return_sequences = False))
    model.add(Dense(1))
    model.add(Activation('softmax'))
    
    adam = optimizers.Adam(lr=0.001)
    model.compile(loss = 'categorical_crossentropy',optimizer = adam , metrics = ['accuracy'])
    return model

# model = KerasClassifier(build_fn = vanilla_rnn , epochs = 200 , batch_size = 2 , verbose = 1)
# model.fit(train_x,train_y)

# y_pred = model.predict(train_x)
# y_test_ = np.argmax(y_test, axis = 1)

# print(accuracy_score(y_pred , y_test_))

In [64]:
model = KerasClassifier(build_fn = vanilla_rnn , epochs = 1 , batch_size = 2 , verbose = 1)

C:\Users\jatpradh\AppData\Local\Temp\ipykernel_10168\3315837755.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  model = KerasClassifier(build_fn = vanilla_rnn , epochs = 1 , batch_size = 2 , verbose = 1)


In [65]:
train_x.shape

(16, 40)

In [66]:
train_x = np.reshape(train_x,(16,40,1))

In [67]:
train_x[1]

array([[  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [219],
       [ 24],
       [  2],
       [114],
       [220],
       [221],
       [  4],
       [222],
       [223],
       [  3],
       [115],
       [224],
       [ 14],
       [  5],
       [225],
       [116],
       [ 25],
       [  9],
       [  1],
       [117],
       [106],
       [ 67],
       [118],
       [ 44],
       [ 45],
       [226],
       [ 24],
       [ 10],
       [227],
       [228],
       [ 29],
       [229],
       [119],
       [114]])

In [68]:
train_y.shape

(16,)

In [69]:
train_y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [70]:
train_y[1]

0

In [71]:
train_y.shape

(16,)

In [72]:
train_y = np.reshape(train_y,(16,1))

In [73]:
train_y

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])

In [74]:
train_y[1]

array([0])

In [75]:
model.fit(train_x,train_y)

C:\Users\jatpradh\Anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


8/8 [==============================] - 2s 5ms/step - loss: 0.0000e+00 - accuracy: 0.5000 


In [76]:
train_x[1]

array([[  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [219],
       [ 24],
       [  2],
       [114],
       [220],
       [221],
       [  4],
       [222],
       [223],
       [  3],
       [115],
       [224],
       [ 14],
       [  5],
       [225],
       [116],
       [ 25],
       [  9],
       [  1],
       [117],
       [106],
       [ 67],
       [118],
       [ 44],
       [ 45],
       [226],
       [ 24],
       [ 10],
       [227],
       [228],
       [ 29],
       [229],
       [119],
       [114]])

In [77]:
train_x[1].shape

(40, 1)

In [78]:
model.predict(train_x[1])

2/2 [==============================] - 0s 4ms/step


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [79]:
# Above is the reshape problem

In [80]:
model.predict(np.reshape(train_x[1],(1,40,1))) # how to read - 1 Matrix of size 40X1

1/1 [==============================] - 0s 263ms/step


array([[1]])